---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./metrics-server/ks.yaml
  - ./namespace.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./spegel/ks.yaml
