---
apiVersion: v1
kind: Service
metadata:
  name: garage-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: rpc
      port: 3901
      targetPort: 3901
