---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./configmaps.yaml
- ./externalsecrets.yaml
- ./grafanadashboard.yaml
- ./helmrelease.yaml
- ./ocirepository.yaml
- ./serviceaccount.yaml
- ./storageclasses.yaml
- ./volumesnapshotclasses.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ceph-cluster-dashboard
    files:
      - ceph-cluster.json=./dashboards/ceph-cluster-2842-r18.patched.json
  - name: ceph-osd-dashboard
    files:
      - ceph-osd.json=./dashboards/ceph-osd-5336-r9.patched.json
