---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./configmaps.yaml
- ./externalsecrets.yaml
- ./grafanadashboard.yaml
- ./helmrelease.yaml
- ./ocirepository.yaml
- ./serviceaccount.yaml
- ./storageclasses.yaml
- ./volumesnapshotclasses.yaml
