---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app modded
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: modded
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          00-copy-prometheus-exporter-config:
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.37.0
            command:
              - /bin/sh
              - -lc
            args:
              - |
                set -euo pipefail
                mkdir -p /data/plugins/PrometheusExporter
                cp /config/prometheus-exporter/config.yml /data/plugins/PrometheusExporter/config.yml
          01-fix-bluemap:
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.37.0
            command:
              - /bin/sh
              - -lc
            args:
              - |
                set -euo pipefail
                mkdir -p /data/plugins/BlueMap
                if [ ! -f /data/plugins/BlueMap/core.conf ]; then
                  echo 'accept-download: true' > /data/plugins/BlueMap/core.conf
                  exit 0
                fi
                sed -i 's/^accept-download: false$/accept-download: true/' /data/plugins/BlueMap/core.conf || true
        containers:
          modded:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2025.12.0-java21
            env:
              EULA: "true"
              TZ: America/Toronto
              TYPE: "PAPER"
              VERSION: "1.21.11"
              ONLINE_MODE: false
              SERVER_NAME: *app
              DIFFICULTY: easy
              OPS: "MrPurgen"
              MAX_PLAYERS: 40
              KEEP_INVENTORY: true
              ENABLE_ROLLING_LOGS: true
              ALLOW_FLIGHT: true
              INIT_MEMORY: 1G
              MAX_MEMORY: &max-memory 12G
              PLUGINS: https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.2/minecraft-prometheus-exporter-3.1.2.jar
              MODRINTH_PROJECTS: |
                bluemap
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 2
                memory: *max-memory
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      modded:
        controller: minecraft
        annotations:
          mc-router.itzg.me/externalServerName: "modded.${SECRET_DOMAIN}"
        ports:
          game:
           port: &game-port 25565
          rcon:
           port: &rcon-port 25578
          http:
            port: &web-port 8100
          metrics:
            port: &metrics-port 9940
    serviceMonitor:
      modded:
        endpoints:
          - interval: 30s
            path: /metrics
            port: metrics
            scrapeTimeout: 10s
        serviceName: modded
        labels:
          release: prometheus
    route:
      modded:
        hostnames: ["bluemap-modded.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *web-port
            matches:
              - path:
                 type: PathPrefix
                 value: /
    persistence:
      tmp:
        type: emptyDir
      prometheus-exporter-config:
        type: configMap
        name: modded-prometheus-exporter-config
        globalMounts:
          - path: /config/prometheus-exporter
            readOnly: true
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
