---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly
  namespace: dragonfly-system
spec:
  jobLabel: dragonfly
  namespaceSelector:
    matchNames:
      - dragonfly-system
  podMetricsEndpoints:
    - port: admin
      path: /metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly

