apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:csNH1OZA7H3PmknPniiARtnK6lHSpWgQJuJhlLwH7lXMgo8E3Yn/0ICldZIghLwlLJJr0nGgSIau4lF65IWPqwlpWaB+yaUjX2e4VRBE/WHTZp4g0uiRPUF+EYDHjq/d+i4D25PYsg6JgXuKab3BhEC4LDnXe+EkeGpIPdDIY7ALL7mib5u+g3LqpViNas/At9y2aE4lwkRn5ezpvy6KTXYW/vQ9uIKwdPJo699k/7XK9os8x84IrjN44fxRcYvVJwvh8ZgReNOgMaayS95UAhf+PQTYkUZZQKhockVCf7AAnOadGTVSCTxn3e/8G8cabfnxBQy4B5T4NWH66/si9rIvv3AbLSEED10GumXiB3fQLtkOhuQb1/0J/NSaTCyxELOXnpPC/eZR9qVNJYiRTl1Jkex6EQS4XdwWLN2IS2737IPdKDA25g9330A06FjKN0UbBYou3QbbPEispbdZ+lOwbk4X5hp+or7yUlgAZ15gYd+fah92Sjj4FDTtQEzD80vTb8aaCKZCNb6zrRNq5+koHS5usMw5EKtPY++Jf/vXpyJiB2u9nxkV5xNojzK/xaN4TIE1EikpX72JZnigfUNJ/h+utJy7cqceP8MpNvtV3OhoMj9RUOukZ0aBYa+A3LDV8VNXjlXqctAM0AQCeoythd7MpQ1RkM2zXt7pSiBPusKPXnxgtK79AcR0oIcVG8PwlbYxgZCC/sOrIlZmqeA+3tnRnAgQrDGNs5vmtVnwtqKSSbaWM3TgOAovlCAfn7soatDU9NxJM2GsuJlpgHhNnijuHKCWGTf4rLlkYP5XBhIycwjxx7kTQKJr4V7tIJdFJydJRLMBJMxQ7vsGVdu4MuSU2Vp6BOhPvP+30Zr4XrlHq3ITijxBt8WxI9FPpkPpz7d6VIwlO4V46zrgBXZ5z/+rK4p/TVucqgOL+jiLrj01nSMJyTRvpVNefubpQsAGA+i2auXmMZvAsYLcw3WWxzYmwx4X+zBlOo+0ArSiqMxKQLeR+ZWAltexfShCR/gWecja9u+yp2xkhoWqRhGFJVqzvVMJ7P+qQtZaJPNJfBPLogqUwvA1lZ6zUOaJEEpNbaGQ0LCZjtQW/ayfw5eS0mH1EKhkB3mXE21nlf2nMTC6,iv:mauWpxEGl8APeckG+52DcTb3M+pEAWmcQ/0bZvUnovQ=,tag:Ydlh8/q2uWEkDhs8QODBKA==,type:str]
sops:
    age:
        - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVjhHcjI4RzlHb00yQld3
            MW5MSllDUVRQZTUyMFdCdkxKMW5iQ2tKVFNNCko1MFpiZVovT1ZVdHhreFdpUEky
            K2hwcVVTREtiYVUrMXphWU1vVEQ2MWMKLS0tIE1qYzE0WjhBTlNQL1l4OUN5eXVK
            QXllUWVBWlRkWXVjMnluWk9WVkplZ1kK9+35gHg+Qt0otH59+ieQGrtgb5ti88rz
            nbiopVW5Uz9jJfmewLa2M8bwIoBdc0/WimQ1IZKC11anrvEb/8nteg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T14:51:29Z"
    mac: ENC[AES256_GCM,data:F3DJx/mf5RPlnHGIgm/LWblH6GejNkln+0Ref4EtAnlVkq6JYOmiaOjKsFX+/Ed4wWRQlF1KgQmYXmdr7phpazUoB3ddoooaQtFADvyUYsduvOhF0m/FeMo+K60CQkdEo5pqi8kSAlx73wba6+JeHXwNKKr4GVXB1yizu90YiP4=,iv:SmSzUwAASB6paW/LtKwRLFCdOxZTHUELldhjyvKCGLo=,tag:c2jpW7gbUnyomdUJt8/weA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
