apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZRkWb3nF7giy5TDZbgNYAmwJugfX/8N/3FtcnoSsHdYCnqsFQCqyDQ==,iv:gCH+FLl4PFFwVgGpCbeX59eD5LvfnQjsOepdcW6cZLU=,tag:fEmmsgyOiW78aIbuLsxZqQ==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIajI3djljenk5cVZHbkdZ
        OHJQYnowTm5weFQ4QmxVVzFrYnhwL1lTSGgwCnJNZm9oa0F1SmsrWjc5azl6WEZY
        dmwwUUxyTWZNa25jdzU2ckFIT2t2SjQKLS0tIDdDa0c5dXFZanlvTVpSTTl3TThn
        dmhXbmlQNEtvUVJhY1NvTmlnempMY1UKmqDsuh0wbmSqjlJCZhrMTBjD3FrCxTaH
        WnUb2205+2PSzPF5gCB3q8oBJYDVzXLk+eYNRAhl2cfTkzDy5TtsuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T01:05:38Z"
  mac: ENC[AES256_GCM,data:sbXq1Bc7d+rYfWbfKoUrPbrJRPvevsAT5Umxk8glqoa1Sftw4FdDB9lnl2N0eafQW0oW7OVOd168/uk2JOnkwlodRVeTzE/IDTnRMm969tC1np6RdHSMADGG5CTFOvRuY1ZKJR9KaaUmTSAQqAwYQ0xlY6Z3ofeJJgnbzAzQ6rM=,iv:fTscor4Mk8jWqi0Gs+bfE+SfDD0II9cqfIAuw5+Paxc=,tag:3z/Y/f8fJ+848pq79iFEEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
