apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:p8J/5ht8d0n/nKJgnsNyFRdMWahNDUcN7LwrnXcTs3ZvWURnFEp28A==,iv:6fYKbQKCjSn5vehrXU5sp+R3uzY+HPrg9RZpG54IIAs=,tag:VjwwQaWru94M0yr/twb3lg==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUJlZ1VLd3p6SFpDbytQ
        YVhNMDkxS1hEZXlpVTdBYVBZajJNS1Q5SUZjCkROTWpkZ3ZBM3RGTHBNV0xNTno0
        cHFCNS9RTjduTXUzRW1CWUNjM3ZYOGsKLS0tIDBQVjZUYnZveGI0TGhEVWkwYTlO
        M3BRdEZPQmtPd0hDVG43eWVUbm9rNjAKKBQs9y7Eo3RSCALJ/P2n4x/TE3U43jdz
        EmQdQZiuF3ilUcfgGo9eKBEz9OpkALQWwaapb4ISDYCNpagR2JZ2Kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-24T23:39:22Z"
  mac: ENC[AES256_GCM,data:DXP1al9+qCA8xTQURvy+pLL8tRxQe5H480P3155+xGRdR91+NS/a+JR9npBZiGjKWpNxzDBJCo/BzClYEDfNSumfidIOyD24cv0T7OJVUcHNdn7THBAdzuQsGP4lWYK+xYVM2CAk05SE6eE8fvmqLxxUilDrENYnzeOnIOdkbDc=,iv:DW/Ml0nkJ/K7yVqIIxIBpCimYj+Y6bfz2v9fgPXexIo=,tag:CROBIlAOYIw2g2ERppu2fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
