---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/poddisruptionbudget-policy-v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csi-nfs-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: csi-nfs-controller
