---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./externalsecret.yaml
  # PVC with Volume Populator pattern - uses dataSourceRef to ReplicationDestination
  # This PVC will automatically populate from ReplicationDestination when created
  # Note: For restore scenarios, delete existing PVC first, then this will be created and populated
  # - ./pvc.yaml
  - ./replicationdestination.yaml
  - ./replicationsource.yaml
