apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:6CEQMKTxSJ1XA00=,iv:AdFVPPHbZ0ULVfnOP5WA39fxqcv38EKAAaGVLKXhIAM=,tag:DVQGkoeyPc91GvzoTrkjMg==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:vxRKJDFdJAJPFBI=,iv:T8fCPIoJ/OpuTjhEhSFGkNsu5RoJGKMRPMHjrqEYaCI=,tag:ktbD0+VJ+P3Gk05JMbGRqQ==,type:str]
sops:
    age:
        - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZTFrRHdhQURNcWRtcUh6
            OEhMUHM1dWFWSVNFYXhCVlZ1RGgwOHlpbENnCk5OdHR4VHpBZVQvVDVGTnR4T1Zq
            ajN2SHA3K3hPdjN2SEE5a05RUVBXTGMKLS0tIFQ0K2FMMFhQT3FvVWMyNFJTUllX
            ekN2VVBuU2Y2czFudStIcno0SmJsWG8KFZn0Mfs8c0Ziwc1gM06ePlfBdt3MkHPw
            dGUAveeIDlaMDMBre8tKtM8cBizUE9v66YXRgyU45IHwHogDdu8gNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T11:20:17Z"
    mac: ENC[AES256_GCM,data:ZHrpWNxW1vqs5T3Fcpl2Wc8nssfhT98Tg3P8Y+tU9lQZ+nt0V29Y6kOsEXPvJn7vOwlxvZ2ZmCVMn7KlKt2fgE+tcz1fxrtWz3HYOp3+EJig4a4Zzh80eYoy6C11AI9ysMss7jXKBrzdiQFryhwZMo4Nkuzah2FFKCMDFfysNZo=,iv:cAHZVEuLvntUgkCtb+eWxnIb+O46ScMFhK5MiI9oOFk=,tag:jxZMHRvdOLwWwERrZDH4dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
