apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6CEQMKTxSJ1XA00=,iv:AdFVPPHbZ0ULVfnOP5WA39fxqcv38EKAAaGVLKXhIAM=,tag:DVQGkoeyPc91GvzoTrkjMg==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZTFrRHdhQURNcWRtcUh6
        OEhMUHM1dWFWSVNFYXhCVlZ1RGgwOHlpbENnCk5OdHR4VHpBZVQvVDVGTnR4T1Zq
        ajN2SHA3K3hPdjN2SEE5a05RUVBXTGMKLS0tIFQ0K2FMMFhQT3FvVWMyNFJTUllX
        ekN2VVBuU2Y2czFudStIcno0SmJsWG8KFZn0Mfs8c0Ziwc1gM06ePlfBdt3MkHPw
        dGUAveeIDlaMDMBre8tKtM8cBizUE9v66YXRgyU45IHwHogDdu8gNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T01:05:38Z"
  mac: ENC[AES256_GCM,data:K+m/aqcWoIOzLUKi5W7wf5DRnaptFpR4rgnOleUdzbSEr8XxU8dK918bfrZ8S1r28DEXefjnjEC6dTZOfA+vgNLRf6iY26ku3xT72Mirgfu+m4EPEShgUTkSKEh1O7sE8xyl7zwgahhqn3oI9d8d/FAruvCP9rBfVwhyNGyiyhs=,iv:qlUUkhJfzfhj4bG5FQ/BvmVNCk0c2IbaXcc78WpQPks=,tag:Bb0h8YgUHcFIGi4KtICjTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
