apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lJWzM0iljxUTJko=,iv:w9uEzE3AYK1o2MbAXBrvH+qECVP2Z3WALR5XvSr+YRA=,tag:aqryvciBzi1gcRed9v9Ogw==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbEF0dVNRWFBSTHVEUVA4
        dDRGa0UrbXIzNGFjMWJYMVZFaTJwQ0JwM3lnCndJVzEzZU5iaThSM01Hc0Y2UzBE
        b0tsMERFSkdNUURyRUNhQk9hMi9jQU0KLS0tIGhXbGxIMm05bUVuYm1SUFpyYmYr
        bXdacjdVTzBmTEVZSjBLYlBieE1PQXMKfY5utl8X9qWNXyjYSazQJ82G6MNGTZUG
        tpY5fqLJvXMWWA5VRjWsdEeJAdvDiJuXp1DzAISf95KvmVmPJeSYCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-24T23:39:22Z"
  mac: ENC[AES256_GCM,data:pd8///oMyA8TiT2hp1HHoX6V8UGnnYx7jqQHhTYX5NopuEOsLOOKZ5ASleQa7MrNIPdKTLDXIJMXXRX0E+Xnli8l8/WMpYvuQ6eQOvTaWHFHYsgpxF+f45vR26ck4bahyvmV6VOx3pIj8ayutGrb7mSX8sJaQWbpuV+BFZzUitE=,iv:W/EyMJG+8sKXpFAEVkG82/XEHFa685CSjIrRTolHBpU=,tag:uoC9bk2TYF2brSOx664k1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
