---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3EFuYpKlOrd29dn94VLgn5wnM7mb7gOGhn9C8K/uyOY=,iv:hzEgbAhceRz69xa1feXbbatEDVU79uadHdRBR5xiUdc=,tag:yrohvaSYDbGrIZEl89BgEQ==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OXVJSFBOYUpJSWVTWEhs
        elNhcHZWVVgrb3VmbVkvVmFrUWtESXZxbFdzClBYNzQzd0JhcTBWUThsU0Zwcnkx
        cXpYbjBmLytSMENRQTc5ZlNZbnF5NFEKLS0tIEJFVXZwTnp2Q0ZPa1p3ZVNQdXY5
        bzlHTGwxMUlkMDcwNi81eHFBN24zOEkKKKqr2nO24v2RJI0qyoURc9HWmC1cutit
        lCn68+BD+VFGKh01822iSweyY3aUtXnmEVJjt09Vj5miRpEqbxX9kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T01:05:38Z"
  mac: ENC[AES256_GCM,data:+4RCOQOg4D5ZW5ooesW3pFswVSBxBfBLKRWksbWASiDr0DtWXt7EZD9NfGT8VugxffpgvlSPLUJpQiRQC3LLocx9JVy5nUZKxn0HKOWvkU6i5iWmVJY+dTwOlnTud8L3bymqNddltBTL8FYEbACK9Os6lMzUer1OSVuWaRC6e1s=,iv:oaMzt+JY+nwM+mof8WYkc6r7MLt79Er7IFeA7Nrvh+w=,tag:mi5yAGTw7W2gU5i+SK3n0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
