---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
components:
  - ../../components/sops
  - ../../components/alerts
resources:
  - ./modded/ks.yaml
  - ./namespace.yaml
  - ./router/ks.yaml
  - ./survival/ks.yaml
