---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.postgresql-system.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbName "{{ .POSTGRES_DBNAME }}"
        AUTHENTIK_POSTGRESQL__USER: &dbUser "{{ .POSTGRES_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"

        AUTHENTIK_STORAGE__MEDIA__BACKEND: "s3"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .S3_ACCESS_KEY_ID }}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: authentik-media
        AUTHENTIK_STORAGE__MEDIA__S3__REGION: us-east-1
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: https://s3.${SECRET_DOMAIN}
        AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: s3.${SECRET_DOMAIN}/authentik-media

        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .SECRET_KEY }}"

        AUTHENTIK_EMAIL__HOST: "{{ .SMTP_HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .SMTP_PORT }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_PASSWORD }}"
        AUTHENTIK_EMAIL__USE_TLS: "true"
        AUTHENTIK_EMAIL__USE_SSL: "false"
        AUTHENTIK_EMAIL__TIMEOUT: "10"
        AUTHENTIK_EMAIL__FROM: "authentik@${SECRET_DOMAIN}"

        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ index . \"superuser-username\" }}"
        INIT_POSTGRES_SUPER_PASS: "{{ index . \"superuser-password\" }}"

  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: postgres
    - extract:
        key: aws-ses-smtp
  refreshInterval: 30m
