---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/name: authentik
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/name: authentik
