---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs
spec:
  targetNamespace: default
  interval: 1h
  commonMetadata:
    labels:
      app.kubernetes.io/name: docs
  path: ./kubernetes/apps/default/docs/app
  postBuild:
    substitute:
      APP: docs
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false

