- Developer:
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/bpg
    - Library.tf:
        - abbr: LT
          icon: https://library.tf/images/icon192.png
          href: https://library.tf/insights
    - Terraform Registry:
        - abbr: TF
          icon: terraform.png
          href: https://registry.terraform.io/providers/bpg/proxmox/latest

- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
          description: The front page of the internet

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
