---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./actual-budget/ks.yaml
  - ./booklore/ks.yaml
  - ./cv-site/ks.yaml
  - ./echo/ks.yaml
  - ./homepage/ks.yaml
  - ./namespace.yaml
  - ./paperless-ngx/ks.yaml
  - ./swimstats/ks.yaml
  - ./umami/ks.yaml
  - ./wallos/ks.yaml
