---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kubernetes/apps/v1/service.json
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  selector:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: blackbox-exporter
  ports:
    - name: http
      port: 9115
      protocol: TCP
      targetPort: http
