apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:eRhdC0itfh1nsy/P8b1rIGADTNCcVdWYR3MgZQqg/Z0j0jbXmwWTZeUmpk6hU5YWlvYVyMD84NC7XHvzT2KThR/jHodqhg2+pmlqkavYB9VudOhDShjGyqvJW5s/DJg2Ltmea5RKCiDNL7mXK4cnnMMGOcYYi8lu0Go+xahk6aWv4JD2qPuqekF7osxJaNFrCx3KPag1+q3BZXbGs0CDcxzi6711neHahVnAUOoVnf/w/u6z,iv:l3SQbez/6IVc4hh76Poe4t6ozP6fwCIgdKaAlrYGP1U=,tag:8QHacqhox0RMQyTnUJin8g==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dmVybzRRYjVnbkNLdVQy
        bnlRQzQ4dVVaZzlma1dxRG80cWppWWw0UlZFClpsVG9DRzdCR2pLS213NmRoRHB5
        TkIrOHhmakkvWHQvUS9FWU04YmV0bHMKLS0tIFNyQjBBeW5LcTFIOCtXMVAyWnhO
        QVJQakZOcVFzUzFTTk9tUFZuVzMzWmMKnsSYJEUlDFJ16AvcmU3F1pkhDAtQL0A8
        IlkMbYxv5rEml3kULFfZ1LJB4DZVrvUNIW9hjC7TQV5P8ynggCKarA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T01:05:38Z"
  mac: ENC[AES256_GCM,data:FK7cCBzaqxJN5AKCa6S9FQ5INEAvL/fK/uqS0wFC6PePr2E7kE+qXDMilk8wYLvuERJhTQIXAe2q4YPfHXJaaVmW3DX6r4ZQRp5D1CyKokd5KVQ5NW4luA7C/tb6Dyflvjt5b+x8E0/25uhACj7KHZeauX8I2YVe0Xn8H1GbsAU=,iv:7VO8x3Zw35L9rTeV9PffeHbGn7n1ZdIca+A05qSfIM4=,tag:ED2VVA217Vs9kymYjlnlcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
