apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Azs0xU/BdoRcyrWWR0iZQz19dZ3C3YJygsNWNaOEa7oZC3kCWYZLcCwHEcSljyG1zU8xi3VbyS5M3c0WIA/BBVMdTYoW32gAicxtRHjaslvqJ0Zyhf+C+ckSdiaGervA3+1hymlK0E8Mz8b/W/F41BjIkdOY3A0XV2eXzQ+7H4oZX4oXHwbFKAcdjAbWj/MPgeO3+kDUrCJUPZ/TcmhHa6DODVHs3NjL4rmlJk5nE5dlkPmb,iv:XOfZVIFObjq2BTaTf4ueUd1+PwHvalSROeoehklpDGk=,tag:P6lia/2Gx/m8jBKIQdjOhA==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVNIRUJNUysrTjFuNnRG
        TFFlL0pScXF2RjJqNGhOUGdOMDhtNmZiR25zClNYbURGR3lUQjFuV3NUeVZMc2to
        SWdDYWZpeW8rSHFtOUFFNFpXUnJxc1EKLS0tIDR0dTdHcm1BaXZRYjY3N1hmYlVw
        NjlpTEhMeG5OOTBKS0xFUmp3TWZXRHcKr7QsJRk7gSMHuWt3aaNqgM+RWh4ecTOs
        sBapSzSULaeCCpikT1peIW4okPe6giocJgt4kwmthoRs9zhbukhL3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-24T23:39:22Z"
  mac: ENC[AES256_GCM,data:gFD1w6LyT019lVhrqx5X/4o9RlSowtGwPQplS0vkNhspN0sd+qDh/UBpyVxbxtm9NnBOaqU3vf//N2OvbSZ6v1zcpm5yVUMH/xgyEV+uNQ9ZsqMY+xWPTPIi8EPMvNAUYQe3fZzoj5ckCkjI/EzLMRYEegTfhhgad3XMliytD7M=,iv:eQEjeKwcW/3ucnXfqNk3S9qzvPu4VYX3HzOK3Q2OHC0=,tag:zwogn4yLDWKNpeW0QxRysw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
