---
# yaml-language-server: $schema=../../../../schemas/gateway.networking.k8s.io/httproute_v1-subst.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: couchdb
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "CouchDB"
    gethomepage.dev/description: "Document database (Apache CouchDB)"
    gethomepage.dev/group: "Databases"
    gethomepage.dev/icon: "couchdb.png"
spec:
  hostnames:
    - couchdb.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: couchdb-svc-couchdb
          port: 5984


