apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: test-secret-username
      remoteRef:
        key: test-secret/username
    - secretKey: test-secret-password
      remoteRef:
        key: test-secret/password
