---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: swimstats-caddyfile
    files:
      - Caddyfile=./config/Caddyfile
  - name: swimstats-config
    files:
      - config.json=./config/config.json
generatorOptions:
  disableNameSuffixHash: true
