---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./serviceaccount.yaml
configMapGenerator:
  - name: swimstats-caddyfile
    files:
      - Caddyfile=./config/Caddyfile
generatorOptions:
  disableNameSuffixHash: true
