---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Location
        HOMEPAGE_VAR_LATITUDE: "{{ .LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .LONGITUDE }}"
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARED_ACCOUNTID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARED_TUNNELID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARED_API_TOKEN }}"
        HOMEPAGE_VAR_OPNSENSE_USERNAME: "{{ .OPNSENSE_USERNAME }}"
        HOMEPAGE_VAR_OPNSENSE_PASSWORD: "{{ .OPNSENSE_PASSWORD }}"
        HOMEPAGE_VAR_TRUENAS_APIKEY: "{{ .TRUENAS_APIKEY }}"
        HOMEPAGE_VAR_PROXMOX_API_USER: "{{ .PROXMOX_API_USER }}"
        HOMEPAGE_VAR_PROXMOX_API_USER_KEY: "{{ .PROXMOX_API_USER_KEY }}"
        HOMEPAGE_VAR_PAPERLESS_NGX_API_TOKEN: "{{ .PAPERLESS_NGX_API_TOKEN }}"
        HOMEPAGE_VAR_NEXTDNS_PROFILEID: "{{ .NEXTDNS_PROFILEID }}"
        HOMEPAGE_VAR_NEXTDNS_API_TOKEN: "{{ .NEXTDNS_API_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_API_KEY: "{{ .UNIFI_API_KEY }}"
        HOMEPAGE_VAR_UPTIME_ROBOT_API_KEY: "{{ .UPTIME_ROBOT_API_KEY }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GF_SECURITY_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GF_SECURITY_ADMIN_PASSWORD }}"
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: cloudflare
    - extract:
        key: opnsense
    - extract:
        key: nextdns
    - extract:
        key: grafana
