---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql-system

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./barman-cloud-plugin/ks.yaml
  - ./postgres-cluster/ks.yaml

