apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:U4hJwF7obTs0CE07h4n0mBAaC2L1ZKs3iaJzcqVfUk3BiaF4YAO1Kg==,iv:jhydhlWv+RBkTimhnzxvY8lUrRFgkw9njsn78KHB5D0=,tag:YaWGK9QyflQ8brd8yEIFww==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYmJreU81bFRoVGhlWXl5
        Y0RyWjQydDUrTlRoUzNpS21uOW1MaFBvcWswClhPcDZnQ1VRRGFObWIrZXhQeFhF
        SnRhcTluY2RHUlVROFE1MlN6ZXZZRjQKLS0tIEZmT3hWYUh4d0gzVFd5bWJCeE93
        UWl1em4ySkVlcEZZWi8zY3JvQ3YzYjAKBxeLR77biN3gKx/NrGB85hjvZQjQ/2lT
        5Xecne9nG1ehoA+maK9TaAyHOFkzUrwa2UA0Xa9rnxYWK9Ee1hQCtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T01:05:38Z"
  mac: ENC[AES256_GCM,data:MMpoSFo8C6BVkJZnD6DtnO9CuWbrCQg/WOH4Ts2y7dLjmY0TC4/cPwZDzfS/mivPJ9TFLCL1TAgSdbUJpmuwWyub3XJk0jzpDv4CxkjdDGeIQw8wi7tFWK4lzBxhds2PmtwbSpitawekN7AMHG1Tr9SBbgfgVvnfcs69NT7Vw+E=,iv:xEh80/MnceeGAITPQpmQpUSYV86i30rtm0lRjQf9RnI=,tag:glraVGInIZnYyRm3xH1EKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
