apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vkw+qfBDv4VKIHofglnFSqSDiFYmEFh0qdTif2ZOLwTaysKnFbrmVQ==,iv:yE61n4oTlDZDNwXRS7MyRS9fLluYXa4WlaIN7rz1f3c=,tag:3bgyvVnfZvBfRGdsBxDvRg==,type:str]
sops:
  age:
    - recipient: age1myf2juvn2dp5m4vpty48725cxnlt9stja0tcljs0vmf64zg4ja4q2ej562
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MkJ4WmxSLzZMNnE4V2dV
        dUorUFBhbXQwdEZKZW1yNmY3N0g2Wml1eEhNCm80T1NBMDZoN1lEK3R6SU1WOVJn
        bkptdGMzSHNRT0hJRG9BZE5xMGx4WUkKLS0tIFJ4RDBkRFJabXlTN29TOEQxYnpv
        bjVtbEtQdGlRTzZ1OUdwV01UMEg1RTgKHj2+zm4R/khGP75CI6QK1seubdHY4gZ8
        aAoJJon+Fz6X2Xh/S702C4jWMxLIZbnzh8m2RvQgxQoVDi+JZZ2ikA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-24T23:39:22Z"
  mac: ENC[AES256_GCM,data:qP5lm7ZNlogDIhrfbL7sK25Doxspj7J0gFM+MLymGiSCd4SMZc3z5+0RkVI0iTtrKFCXKyps3BpGpl6v8gcqnIw+f4su13kulksYZ5D/tSlZV/kb1G8GoK36MnsgeeK8dhatkklJlT7VSDIX6+R9eEuQn+qG+596NIKvKUSFxAE=,iv:ufIAt7hgfOW8KJCHbm+SFyQ/lTGq5xC3JMFqvYn4a7c=,tag:OiJP56Yg/6RYxL3qSeOLBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
