---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: booklore-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # MariaDB connection for BookLore (localhost since sidecar)
        DATABASE_URL: "jdbc:mariadb://localhost:3306/booklore"
        DATABASE_USERNAME: booklore
        DATABASE_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        # MariaDB container env vars
        MYSQL_ROOT_PASSWORD: "{{ .MYSQL_ROOT_PASSWORD }}"
        MYSQL_PASSWORD: "{{ .DATABASE_PASSWORD }}"
  dataFrom:
    - extract:
        key: booklore
  refreshInterval: 30m
