---
# Application secrets for Umami
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: umami-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP_SECRET: "{{ .APP_SECRET }}"
        DB_NAME: "{{ .DB_NAME }}"
        DB_USER: "{{ .DB_USER }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DATABASE_URL: "postgresql://{{ .DB_USER }}:{{ .DB_PASSWORD }}@postgres-rw.postgresql-system.svc.cluster.local:5432/{{ .DB_NAME }}"
  refreshInterval: 4h
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: umami/app-secret
    - secretKey: DB_NAME
      remoteRef:
        key: umami/postgres-database
    - secretKey: DB_USER
      remoteRef:
        key: umami/postgres-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: umami/postgres-password

---
# Superuser credentials to bootstrap the database/user for Umami
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-postgres-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: umami-postgres-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  refreshInterval: 4h
  data:
    - secretKey: username
      remoteRef:
        key: postgres/superuser-username
    - secretKey: password
      remoteRef:
        key: postgres/superuser-password

