---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: umami
spec:
  chartRef:
    kind: OCIRepository
    name: umami
  interval: 1h
  values:
    controllers:
      umami:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/umami-software/umami
              tag: postgresql-latest
            env:
              BASE_PATH: /um
              DATABASE_TYPE: postgresql
              DISABLE_TELEMETRY: "1"
              HOSTNAME: "pavel.${SECRET_DOMAIN}"
              NEXT_PUBLIC_APP_URL: "https://pavel.${SECRET_DOMAIN}/um"
              NODE_ENV: production
              TRACKER_SCRIPT_NAME: um.js
            envFrom:
              - secretRef:
                  name: umami-config
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      tracker:
        controller: umami
        ports:
          http:
            port: 3000
      admin:
        controller: umami
        ports:
          http:
            port: 3000
    route:
      tracker:
        hostnames:
          - "pavel.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /um/api
            backendRefs:
              - identifier: tracker
                port: 3000
          - matches:
              - path:
                  type: PathExact
                  value: /um/um.js
            backendRefs:
              - identifier: tracker
                port: 3000
      admin:
        hostnames:
          - "umami.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: admin
                port: 3000

