---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./db-bootstrap-job.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute-tracker.yaml
  - ./ocirepository.yaml
  - ./pdb.yaml
