---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cv-site
imagePullSecrets:
  - name: cv-site-registry-secret

