---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly-system

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./dragonfly/ks.yaml

