---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly-system

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./dragonfly/ks.yaml
  - ./namespace.yaml

