---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notifications
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/flux-system/notifications/app
  prune: true
  targetNamespace: flux-system
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Alert
      name: flux-system
      namespace: flux-system
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Provider
      name: slack
      namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
