---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: barman-cloud-plugin
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: postgresql-system
  interval: 1h
  path: ./kubernetes/apps/postgresql-system/barman-cloud-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: postgresql-system
  wait: true

