---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backup.yaml
  - ./cluster.yaml
  - ./externalsecrets.yaml
  - ./grafanadashboard.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./volsync.yaml
