---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter
  labels:
    app.kubernetes.io/name: prometheus-pve-exporter
spec:
  selector:
    app.kubernetes.io/name: prometheus-pve-exporter
  ports:
    - name: http
      port: 9221
      targetPort: http
      protocol: TCP
