---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: garage-operator
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/storage/garage-cluster/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
        optional: false
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-webui
  namespace: flux-system
spec:
  dependsOn:
    - name: garage-cluster
  interval: 1h
  path: ./kubernetes/apps/storage/garage-cluster/webui
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
        optional: false
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
