---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-syslog
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: fluent-bit
  ports:
    - name: syslog
      protocol: UDP
      port: 5514
      targetPort: 5514
      nodePort: 30514
