---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/poddisruptionbudget-policy-v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: volsync
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: volsync
      app.kubernetes.io/name: volsync-perfectra1n
