---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/poddisruptionbudget-policy-v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/poddisruptionbudget-policy-v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets-cert-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-cert-controller
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/poddisruptionbudget-policy-v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-webhook
