---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets-cert-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-cert-controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-webhook
