---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./garage-cluster/ks.yaml
  - ./garage-operator/ks.yaml
  - ./namespace.yaml

